### PR TITLE
Update santiy test to use ginkgo.

### LINKED ISSUE #9: Use ginkgo for sanity test
This have several benefits that:
1. Using consistent testing framework as e2e test
2. Able to define multiple test configurations per: https://github.com/kubernetes-csi/csi-test/tree/master/pkg/sanity
3. Test results will be print to stdout as test runs as opposes to stuck
    for a while and dump all results at once in the old way

### PR DESCRIPTION
**Pull request by leakingtapan**
Fix #9 

This have several benefits that:
1. Using consistent testing framework as e2e test
2. Able to define multiple test configurations per:
https://github.com/kubernetes-csi/csi-test/tree/master/pkg/sanity
3. Test results will be print to stdout as test runs as opposes to stuck
for a while and dump all results at once in the old way

Tested using `make test-sanity` and tests are passing.

### CODE REVIEW

**Comment by d-nishi** [comment]
@jsafrane @gnufied --- can you please review this?

**Comment by jsafrane** [comment]
Do we have bots running here? Merging manually.

**Comment by d-nishi** [comment]
@leakingtapan - this will take effect when we move to kubernetes-sigs - I should send the email tomorrow. Closing on Fossabadge issue on licensing.

**Pull request merged**
